#!/usr/bin/env python3
"""Embed editable viewer assets into the C exporter; no runtime asset files needed."""
from pathlib import Path
import argparse
import json

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true', help='fail if the checked-in header is stale')
args = parser.parse_args()
for dimension in (2, 3):
    html = (root / f'viewer/graph{dimension}d.html').read_text()
    html = html.replace('/* VIEWER_CSS */', (root / 'viewer/graph3d.css').read_text())
    sampler = 'sampler.js' if dimension == 3 else 'sampler2d.js'
    js = '\n'.join((root / 'viewer' / name).read_text() for name in ['math.js', sampler, f'graph{dimension}d.js'])
    html = html.replace('/* VIEWER_JS */', js)
    head, tail = html.split('/* GRAPH_DATA */')
    result = '/* Generated by tools/embed_viewer.py. Edit viewer/ sources, then regenerate. */\n'
    for name, value in [(f'GRAPH{dimension}D_HTML_HEAD', head), (f'GRAPH{dimension}D_HTML_TAIL', tail)]:
        result += f'static const char {name}[] =\n'
        result += '\n'.join(json.dumps(line, ensure_ascii=False) for line in value.splitlines(keepends=True)) + ';\n'
    path = root / f'src/graph{dimension}d_viewer.h'
    if args.check:
        if not path.exists() or path.read_text() != result:
            raise SystemExit('Viewer header is stale. Run python3 tools/embed_viewer.py')
    else:
        path.write_text(result)
