#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "codegen.h"
#include "symtab.h"
#include "errors.h"

#ifdef _WIN32
#include <direct.h>
#define MKDIR(path) _mkdir(path)
#else
#include <sys/stat.h>
#define MKDIR(path) mkdir(path, 0755)
#endif

static char pool[64][40];
static int  pool_i = 0;
static int  next_temp;

static char *next_buf(void) {
    pool_i = (pool_i + 1) % 64;
    return pool[pool_i];
}

/* The distinct variable names read by an expression, so their
 * CURRENT MathScript values can be embedded as C constants at the
 * top of the generated program (see docs/GRAMMAR.md, "Code
 * Generation" example). Collection itself lives in ast.c so
 * graph.c and solver.c can share it. */
#define MAX_VARS 32
static char var_names[MAX_VARS][64];
static int  var_count;

static const char *c_function_name(const char *ms_name) {
    if (strcmp(ms_name, "abs") == 0) return "fabs";
    return ms_name; /* sqrt, pow, sin, cos, tan, log map 1:1 onto <math.h> */
}

static const char *codegen_expr(FILE *f, ASTNode *n) {
    char *out = next_buf();
    switch (n->kind) {
        case N_NUM:
            snprintf(out, 40, "%.10g", n->num);
            return out;
        case N_VAR:
            snprintf(out, 40, "%s", n->name);
            return out;
        case N_UMINUS: {
            const char *a = codegen_expr(f, n->left);
            char abuf[40]; snprintf(abuf, 40, "%s", a);
            int t = next_temp++;
            fprintf(f, "    double t%d = -(%s);\n", t, abuf);
            snprintf(out, 40, "t%d", t);
            return out;
        }
        case N_CALL: {
            char args[2][40] = {"", ""};
            for (int i = 0; i < n->argc && i < 2; i++)
                snprintf(args[i], 40, "%s", codegen_expr(f, n->args[i]));
            int t = next_temp++;
            if (n->argc == 2)
                fprintf(f, "    double t%d = %s(%s, %s);\n", t, c_function_name(n->name), args[0], args[1]);
            else
                fprintf(f, "    double t%d = %s(%s);\n", t, c_function_name(n->name), args[0]);
            snprintf(out, 40, "t%d", t);
            return out;
        }
        case N_BINOP: {
            const char *a = codegen_expr(f, n->left);
            char abuf[40]; snprintf(abuf, 40, "%s", a);
            const char *b = codegen_expr(f, n->right);
            int t = next_temp++;
            if (n->op == '^')
                fprintf(f, "    double t%d = pow(%s, %s);\n", t, abuf, b);
            else {
                const char *sym =
                    n->op == '+' ? "+" : n->op == '-' ? "-" :
                    n->op == '*' ? "*" : n->op == '/' ? "/" :
                    n->op == '<' ? "<" : n->op == '>' ? ">" :
                    n->op == OP_GE ? ">=" : n->op == OP_LE ? "<=" :
                    n->op == OP_EQ ? "==" : n->op == OP_NE ? "!=" : "?";
                fprintf(f, "    double t%d = %s %s %s;\n", t, abuf, sym, b);
            }
            snprintf(out, 40, "t%d", t);
            return out;
        }
    }
    snprintf(out, 40, "0");
    return out;
}

int codegen_run(ASTNode *stmt) {
    MKDIR("output");
    const char *c_path = "output/generated.c";
#ifdef _WIN32
    const char *exe_path = "output/generated.exe";
#else
    const char *exe_path = "output/generated";
#endif

    FILE *f = fopen(c_path, "w");
    if (!f) { printf("Code Generation Error: could not write %s\n", c_path); return 0; }

    ASTNode *lhs = NULL, *rhs = stmt;
    int is_assign = (stmt->kind == N_BINOP && stmt->op == '=');
    if (is_assign) { lhs = stmt->left; rhs = stmt->right; }

    var_count = 0;
    ast_collect_vars(rhs, var_names, MAX_VARS, &var_count);

    fprintf(f, "/* Auto-generated by MathScript's code generator (codegen.c).\n");
    fprintf(f, "   Source statement compiled into plain C, then built and run\n");
    fprintf(f, "   with the system C compiler to demonstrate executable-code\n");
    fprintf(f, "   generation, per the MathScript compiler pipeline. */\n");
    fprintf(f, "#include <stdio.h>\n#include <math.h>\n\nint main(void) {\n");

    for (int i = 0; i < var_count; i++) {
        double v;
        if (symtab_lookup(var_names[i], &v))
            fprintf(f, "    double %s = %.10g;\n", var_names[i], v);
    }

    next_temp = 1;
    const char *result_operand = codegen_expr(f, rhs);

    if (is_assign) {
        fprintf(f, "    double %s = %s;\n", lhs->name, result_operand);
        fprintf(f, "    printf(\"%%g\\n\", %s);\n", lhs->name);
    } else {
        fprintf(f, "    double result = %s;\n", result_operand);
        fprintf(f, "    printf(\"%%g\\n\", result);\n");
    }
    fprintf(f, "    return 0;\n}\n");
    fclose(f);

    printf("Generated C source: %s\n", c_path);

    char cmd[512];
#ifdef _WIN32
    snprintf(cmd, sizeof(cmd), "gcc \"%s\" -O2 -o \"%s\" -lm", c_path, exe_path);
#else
    snprintf(cmd, sizeof(cmd), "cc \"%s\" -O2 -o \"%s\" -lm", c_path, exe_path);
#endif
    printf("Compiling: %s\n", cmd);
    fflush(stdout);
    if (system(cmd) != 0) {
        printf("Code Generation Error: compilation failed.\n");
        return 0;
    }

    printf("Running %s ->\n", exe_path);
    fflush(stdout);
#ifdef _WIN32
    /* cmd.exe's implicit-executable lookup wants a backslash path
       (a quoted forward-slash path like "output/generated.exe"
       is reported as "not recognized"); build.ps1/gcc are fine
       with forward slashes, only this run step needs backslashes. */
    snprintf(cmd, sizeof(cmd), "\".\\output\\generated.exe\"");
#else
    snprintf(cmd, sizeof(cmd), "\"./%s\"", exe_path);
#endif
    int run_status = system(cmd);
    fflush(stdout);
    if (run_status != 0) {
        printf("Code Generation Error: generated program failed to run.\n");
        return 0;
    }
    return 1;
}
